name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096 --openssl-legacy-provider
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run compile
    - name: Test
      run: xvfb-run -a npm run test
